src/lib/components/avatar/QAvatar.svelte
src/lib/components/avatar/index.scss
src/lib/components/list/index.scss
src/lib/css/index.scss
src/lib/utils/props.ts

As mentionned, I tried to start refactoring one of the components (QAvatar) to follow BEM principles and added our own styles to free Quaff from BeerCSS' styles and thus lighten the CSS bundle size.

QAvatar: refactored to use own CSS and BEM classes

---

src/lib/components/button/QBtn.svelte
src/lib/components/button/index.scss
src/lib/components/icon/QIcon.svelte
src/lib/components/icon/index.scss
src/lib/components/progress/QCircularProgress.svelte
src/lib/components/progress/index.scss
src/lib/components/progress/props.ts
src/lib/css/index.scss
src/lib/css/states.scss
src/lib/utils/props.ts

I made multiple changes, the main ones being:
- `QBtn` BEM refactoring, using the new `createClasses` capabilities and the new circular progress component
- Created a `QCircularProgress` component (only indeterminate form for now)
- Created a `states.scss` file, which contains reusable styles related to element states (disabled, ripple, transparent, etc.)
The rest is minimal like moving some styles and importing all the necessary.

Kil refactors

---

src/lib/components/button/QBtn.svelte
src/lib/components/button/index.scss
src/lib/components/chip/QChip.svelte
src/lib/components/chip/index.scss
src/lib/components/chip/props.ts
src/lib/components/private/QDocs.svelte
src/lib/css/mixins.scss
src/lib/css/states.scss
src/routes/components/button/+page.svelte
src/routes/components/chip/+page.svelte
src/routes/dev/+page.svelte

- Refactored QChip so it follows BEM principles
- Added a btn-image mixin to be able to reuse the styles
- Added possibility to add image to QBtn with `icon="img:/cotcktail.jpg"`

QChip: BEM refactor

---

src/lib/components/input/QInput.svelte
src/lib/components/input/index.scss
src/lib/components/select/QSelect.svelte
src/lib/components/select/index.scss
src/lib/css/index.scss
src/lib/css/mixins.scss
src/lib/css/mixins/field.scss
src/lib/css/mixins/menu.scss

Please note how I put some mixins as separate files in the newly created `mixins` directory. I think the `mixins.scss` would've gotten too big otherwise.

feat: QInput, QSelect: refactored to BEM. added mixins.

---

src/lib/components/breadcrumbs/QBreadcrumbs.svelte
src/lib/components/dialog/QDialog.svelte
src/lib/components/dialog/props.ts
src/lib/components/drawer/QDrawer.svelte
src/lib/components/list/QList.svelte
src/lib/components/tabs/QTab.svelte
src/lib/helpers/clickOutside.ts
src/routes/components/layout/+page.svelte
src/routes/dev/+page.svelte

Changed some minor things to improve performance and readability

Performance and readability fixes

---

package-lock.json
package.json
pnpm-lock.yaml
src/lib/components/icon/QIcon.svelte
src/lib/components/icon/index.scss
src/lib/components/icon/props.ts
src/lib/components/index.ts
src/lib/components/toolbar/QToolbarTitle.svelte
src/lib/components/toolbar/index.scss
src/lib/components/toolbar/props.ts
src/lib/composables/use-size.ts
src/lib/css/fonts.scss
src/lib/css/theme/elevate.scss
src/lib/css/theme/palette.scss
src/lib/css/theme/reset.scss
src/lib/css/theme/theme.dark.scss
src/lib/css/theme/theme.light.scss
src/lib/css/theme/theme.scss
src/lib/css/theme/typography.scss
src/routes/+layout.svelte
src/routes/colors/+page.svelte
src/routes/components/icon/+page.svelte
src/routes/components/layout/+page.svelte
src/routes/components/layout/docs.snippets.ts
src/routes/dev/+page.svelte
src/routes/layout/+page.svelte

Just noticed that I need to refactor the `typography.scss` after merging to remove some classes - it's on my watch!

More refactors

---

src/lib/components/avatar/QAvatar.svelte
src/lib/components/avatar/props.ts
src/lib/components/button/QBtn.svelte
src/lib/components/button/props.ts
src/lib/components/chip/QChip.svelte
src/lib/components/chip/props.ts
src/lib/components/drawer/QDrawer.svelte
src/lib/components/drawer/props.ts
src/lib/components/footer/QFooter.svelte
src/lib/components/footer/props.ts
src/lib/components/icon/QIcon.svelte
src/lib/components/icon/props.ts
src/lib/components/progress/QCircularProgress.svelte
src/lib/components/progress/props.ts
src/lib/components/railbar/QRailbar.svelte
src/lib/components/railbar/props.ts
src/lib/components/toolbar/QToolbar.svelte
src/lib/components/toolbar/props.ts
src/lib/composables/use-size.ts
src/lib/utils/types.ts

- Created a `useSize` function to handle all different sizes that could be received as input from users
- Wrote some types related to sizes
- Refactored some components to use the `useSize` function
- Added some default values for some components' props to be used in docs

refactor(size): created a better useSize function

---

src/lib/components/drawer/QDrawer.svelte
src/lib/components/drawer/index.scss
src/lib/components/footer/QFooter.svelte
src/lib/components/footer/index.scss
src/lib/components/footer/props.ts
src/lib/components/header/QHeader.svelte
src/lib/components/header/props.ts
src/lib/components/index.ts
src/lib/components/layout/index.scss
src/lib/components/list/index.scss
src/lib/components/private/QApi.svelte
src/lib/components/railbar/QRailbar.svelte
src/lib/components/railbar/index.scss
src/lib/components/toolbar/QToolbar.svelte
src/lib/components/toolbar/index.scss
src/lib/components/toolbar/props.ts
src/lib/css/index.scss
src/lib/css/mixins.scss
src/lib/css/states.scss
src/lib/utils/props.ts
src/routes/+layout.svelte
src/routes/components/layout/+page.svelte

Refactored QLayout. It's been a real hassle so expect some bugs. No bugs were found yet, even without BeerCSS imported.
Also fixed some styles.

Qlayout refactor

---

src/lib/components/button/QBtn.svelte
src/lib/components/button/index.scss
src/lib/components/dialog/QDialog.svelte
src/lib/components/railbar/index.scss
src/lib/components/tabs/QTab.svelte
src/lib/components/tabs/QTabs.svelte
src/lib/components/tabs/index.scss
src/lib/css/index.scss
src/lib/css/ripple.scss
src/lib/helpers/ripple.ts
src/lib/utils/dom.ts
src/lib/utils/events.ts

Lots of things there:
- Added Ripple effect
- Added Ripple to QBtn and QTabs
- Fixed some broken styles
- Refactored QTabs to BEM
- Added keyboard activation events to QBtn and QTabs
- Added keyboard focus events to QTabs

Ripple refactor + QBtn, QTabs and QDialog refactors/fixes

---

src/hooks.server.ts
src/lib/components/button/QBtn.svelte
src/lib/components/button/props.ts
src/lib/components/layout/index.scss
src/lib/components/list/QItem.svelte
src/lib/components/list/QItemSection.svelte
src/lib/components/list/QList.svelte
src/lib/components/list/index.scss
src/lib/components/list/props.ts
src/lib/components/tabs/index.scss
src/lib/css/ripple.scss
src/lib/css/theme/theme.dark.scss
src/lib/css/theme/theme.light.scss
src/lib/helpers/ripple.ts
src/lib/stores/Quaff.ts
src/lib/utils/props.ts
src/lib/utils/types.ts
src/routes/+layout.svelte
src/routes/colors/+page.svelte

Kil refactors 21aug

---

src/lib/css/mixins.scss

Fixed the layout problem mentioned in the issue #35

fix(QLayout): issue 35 - 1.

---

src/lib/components/button/QBtn.svelte
src/lib/components/chip/QChip.svelte
src/routes/components/button/+page.svelte

Finally found a way to properly forward DOM events while still taking into account disabled states

fix(click): properly forwarded DOM click event

---

.prettierignore
src/lib/components/dialog/QDialog.svelte
src/lib/components/dialog/docs.props.ts
src/lib/components/dialog/index.scss
src/lib/components/dialog/props.ts
src/lib/components/private/QDocsSection.svelte
src/lib/components/progress/QCircularProgress.svelte
src/lib/components/progress/QLinearProgress.svelte
src/lib/components/progress/index.scss
src/lib/components/tabs/docs.props.ts
src/lib/css/mixins.scss
src/lib/css/mixins/field-mixins.scss
src/lib/css/shared/q-field.scss
src/lib/css/theme/colors.module.scss
src/routes/components/dialog/+page.svelte
src/routes/components/progress/+page.svelte
src/routes/dev/+page.svelte

- Worked on QProgress and docs
- QField refactor to prevent field growth on focus

13 sep work

---

src/lib/components/avatar/QAvatar.svelte
src/lib/components/breadcrumbs/QBreadcrumbs.svelte
src/lib/components/breadcrumbs/QBreadcrumbsEl.svelte
src/lib/components/button/QBtn.svelte
src/lib/components/card/QCard.svelte
src/lib/components/card/QCardActions.svelte
src/lib/components/card/QCardSection.svelte
src/lib/components/checkbox/QCheckbox.svelte
src/lib/components/chip/QChip.svelte
src/lib/components/dialog/QDialog.svelte
src/lib/components/icon/QIcon.svelte
src/lib/components/list/QItem.svelte
src/lib/components/list/QItemSection.svelte
src/lib/components/list/QList.svelte
src/lib/components/radio/QRadio.svelte
src/lib/components/separator/QSeparator.svelte
src/lib/components/table/QTable.svelte
src/lib/components/toggle/QToggle.svelte
src/lib/components/toolbar/QToolbar.svelte
src/lib/components/tooltip/QTooltip.svelte

Quite big refactor to use Svelte's dynamic class directives instead of "createClasses" to improve performance.
I haven't refactored QLayout components yet due to their complexity and the fact that most of them are not finished yet.
I'll refactor the class when I'll refactor those components completely, I feel like there's already quite a lot to review here.

Classes refactor 10sept

---

.github/pull_request_template.md

- Added a pull request template
N/A
Resolves #62

feat: add a pull request template

---

src/lib/components/radio/QRadio.svelte
src/lib/components/radio/props.ts
src/lib/components/toggle/QToggle.svelte
src/lib/components/toggle/props.ts
src/routes/components/toggle/+page.svelte

- Refactored more components to Svelte 5
N/A
N/A

Svelte 5 refactors coder

---

.eslintrc.cjs

- Add a new ESLint rule to enforce object shorthand syntax
N/A
Closes #67

feat(ESLint): add rule object-shorthand.

---

package.json

- `package.json` scripts should now also run on Windows.
N/A
N/A

refactor(scripts): change scripts to (hopefully) support windows.

---

src/lib/components/table/QTable.svelte
src/lib/components/table/props.ts
src/routes/components/table/+page.svelte

- Migrated QTable to Svelte 5
N/A
N/A

refactor(QTable): migrate to Svelte 5.

---

src/lib/classes/QContext.svelte.ts
src/lib/components/list/QItem.svelte
src/lib/components/list/QItemSection.svelte
src/lib/components/list/QList.svelte

- Improve `QContext` API to avoid unnecessary function calls
- Document the `QContext` class and methods
- Fix some unnecessary uses of `QContext`
- Change QList to use the new API
N/A
N/A

refactor(QContext): change API to make it easier to use

---

src/lib/components/private/QDocs.svelte
src/routes/+layout.svelte
src/routes/components/avatar/+page.svelte
src/routes/components/button/+page.svelte
src/routes/components/card/+page.svelte
src/routes/components/checkbox/+page.svelte
src/routes/components/chip/+page.svelte
src/routes/components/dialog/+page.svelte
src/routes/components/drawer/+page.svelte
src/routes/components/footer/+page.svelte
src/routes/components/icon/+page.svelte
src/routes/components/input/+page.svelte
src/routes/components/layout/+page.svelte
src/routes/components/list/+page.svelte
src/routes/components/progress/+page.svelte
src/routes/components/radio/+page.svelte
src/routes/components/railbar/+page.svelte
src/routes/components/select/+page.svelte
src/routes/components/separator/+page.svelte
src/routes/components/table/+page.svelte
src/routes/components/tabs/+page.svelte
src/routes/components/toggle/+page.svelte
src/routes/components/toolbar/+page.svelte
src/routes/components/tooltip/+page.svelte

- Fixed bugs, migrated QDocs to Svelte 5
N/A
N/A

Refactors and fixes

---

pnpm-lock.yaml
src/lib/classes/QContext.svelte.ts
src/lib/components/tabs/QTab.scss
src/lib/components/tabs/QTab.svelte
src/lib/components/tabs/QTabs.scss
src/lib/components/tabs/QTabs.svelte
src/lib/components/tabs/props.ts
src/lib/css/index.scss
src/lib/utils/dom.ts
src/routes/+page.svelte

- Add a new checker function for reduce motion
- Improve QTabs animation
- Improve QTabs handling of value update
N/A
N/A

Qtab refactor

---

src/lib/css/shared/q-field.scss

- Fixed styles for QSelect in certain scenarios, like in the QTable footer.
N/A
Closes #73

fix(QSelect): adjust QField styles to allow for a shorter input.

---

src/lib/components/toggle/index.scss

- Removed outline from QToggle
N/A
N/A
Closes #84

fix(QToggle): remove unwanted outline.

---

plugins/class-preprocessor/script.js
plugins/class-preprocessor/types.d.ts
src/app.d.ts
tsconfig.json

…heck
- Add TS typing check
- Add a custom component handler to avoid `class:` directives being put on custom components (which Svelte doesn't support)
N/A
N/A

fix(class preprocessor): handle custom components and add TS typing check

---

src/lib/classes/QScrollObserver.svelte.ts
src/lib/utils/dom.ts

- Added an utility to track scroll
N/A
N/A

feat: add a scroll observer utility class

---

src/lib/components/breadcrumbs/QBreadcrumbsEl.scss
src/lib/components/card/QCard.scss
src/lib/components/card/QCardActions.scss
src/lib/components/card/QCardSection.scss
src/lib/components/drawer/QDrawer.scss
src/lib/components/footer/QFooter.scss
src/lib/components/header/QHeader.scss
src/lib/components/layout/QLayout.scss
src/lib/components/railbar/QRailbar.scss
src/lib/components/tabs/QTab.scss
src/lib/components/tabs/QTabs.scss
src/lib/components/tabs/index.scss
src/lib/css/classes/_spaces.scss
src/lib/css/mixins/_image.scss
src/lib/css/mixins/_spaces.scss

- Possibility to add multiple spacings using only one mixin call
> Example: mixins.padding("x-md", "y-sm")
- Add error handling in the gap mixin
N/A
N/A

refactor: improve SCSS spacing API

---

src/lib/components/layout/QLayout.svelte
src/lib/components/list/QItem.svelte
src/lib/components/private/ContextReseter.svelte
src/lib/components/private/QApi.svelte
src/lib/components/switch/QSwitch.scss
src/lib/utils/router.ts
src/routes/components/switch/+page.svelte

- Improve checker for active route
- Fix QItem active class problem adding BEM prefix to user's chosen active class
- Fix context reseter
- Fix QDrawer not showing on custom type click inside QApi
N/A
N/A

Minor improvements and fixes

---

docgen/snippets/parseSvelteFile.ts
package.json
pnpm-lock.yaml
src/lib/components/chip/QChip.scss
src/lib/components/codeBlock/QCodeBlock.svelte
src/lib/components/codeBlock/props.ts
src/lib/components/dialog/QDialog.scss
src/lib/components/private/QApi.svelte
src/lib/components/private/QDocsSection.svelte
src/lib/css/_disabled.scss
src/lib/css/mixins/_design.scss
src/routes/components/avatar/+page.svelte
src/routes/components/button/+page.svelte
src/routes/components/card/+page.svelte
src/routes/components/checkbox/+page.svelte
src/routes/components/chip/+page.svelte
src/routes/components/dialog/+page.svelte
src/routes/components/input/+page.svelte
src/routes/components/layout/+page.svelte
src/routes/components/radio/+page.svelte
src/routes/components/select/+page.svelte
src/routes/components/switch/+page.svelte

- Give "add-transparency" mixin a better name
- Replace highlightjs and svelte-highlight with shiki, allowing more languages and themes
N/A
N/A

Improve syntax highlighting

---

package-lock.json
package.json

0.1.0-prealpha17

---

package-lock.json
package.json

prealpha18

---

package.json

0.1.0-prealpha19

---

.github/workflows/npmpublish.yml
package.json

- Bumped version
- Fixed CI for `bun publish`

Fix bun publish

---

.gitattributes
.prettierrc
src/lib/components/button/QBtn.svelte
src/lib/components/button/props.ts
src/lib/components/codeBlock/QCodeBlock.svelte
src/lib/components/private/QDocsSection.svelte
src/lib/components/table/QTable.svelte
src/routes/+layout.svelte
src/routes/components/button/+page.svelte
src/routes/components/layout/+page.svelte
src/routes/components/select/+page.svelte
src/routes/components/table/+page.svelte
src/routes/dev/+page.svelte
src/routes/layout/+page.svelte

- Added the possibility to choose a variant using boolean attributes
- To avoid variant collisions, I chose a hierarchy: `variant > filled > tonal > outlined > flat > elevated (default)`
- Fixed the problem with prettier eof breaking `bun lint` on Windows
N/A
N/A

QBtn varant API change

---

src/lib/components/input/props.ts
src/lib/components/list/props.ts
src/lib/components/progress/props.ts
src/lib/components/radio/props.ts
src/lib/components/railbar/props.ts
src/lib/components/select/props.ts
src/lib/components/separator/props.ts
src/lib/components/switch/props.ts
src/lib/components/tabs/props.ts
src/lib/components/toolbar/docs.ts
src/lib/components/toolbar/props.ts

- Added prop description and default for component props that didn't have them
N/A
N/A

Docs: Add description and default where needed

---

src/lib/components/drawer/QDrawer.svelte
src/lib/components/private/QDocs.svelte
src/routes/+layout.svelte
src/routes/colors/+page.svelte
src/routes/components/+layout.svelte
src/routes/components/dialog/+page.svelte
src/routes/components/drawer/+page.svelte
src/routes/components/list/+page.svelte
src/routes/components/progress/+page.svelte
src/routes/components/table/+page.svelte
src/routes/components/tabs/+page.svelte

- Fix the problem where changing doc page would rerender the whole layout
- Remove unnecessary code
- Fix some styles
- Fix color page to improve contrast between text and bg in palettes
- Avoid binding multiple dialog and drawer components to the same variable (would induce bugs otherwise)
N/A
Closes #123, #124

Various fixes

---

src/lib/components/button/QBtn.svelte
src/lib/components/progress/QCircularProgress.svelte
src/lib/components/progress/QLinearProgress.svelte
src/lib/components/progress/docs.ts
src/lib/components/separator/QSeparator.scss
src/lib/components/switch/QSwitch.svelte
src/lib/components/tabs/QTab.scss
src/lib/components/tabs/QTab.svelte
src/lib/components/tabs/QTabs.scss
src/lib/components/tabs/QTabs.svelte
src/lib/components/tabs/props.ts
src/lib/components/tooltip/QTooltip.scss
src/routes/+layout.svelte
src/routes/components/checkbox/+page.svelte
src/routes/components/progress/+page.svelte
src/routes/components/radio/+page.svelte
src/routes/components/railbar/+page.svelte
src/routes/components/select/+page.svelte
src/routes/components/separator/+page.svelte
src/routes/components/switch/+page.svelte
src/routes/components/table/+page.svelte
src/routes/components/tabs/+page.svelte
src/routes/components/toolbar/+page.svelte
src/routes/components/tooltip/+page.svelte

- Finish writing components docs
- Add change event for QSwitch
- Remove unecessary prop in QTabs
- Fix styling problem on round QBtn that have a tooltip
- Add custom HEX color support for progress
- Fix some prop and style problems for progress
- Normalize progress values so both 0.5 and 50 (as a percentage) are accepted
N/A
N/A

Finish components docs + some fixes

---

package.json

- add license to `package.json`, as recommended by the build script
N/A
N/A

feat: add license to package.json

---

src/app.html
src/lib/classes/Quaff.svelte.ts
src/lib/components/layout/QLayout.svelte
src/lib/css/theme/_reset.scss
src/routes/+layout.svelte
src/routes/components/layout/+page.svelte

- Fix dark mode not working on client side
- Fix dark mode flashing on load
- Fix QLayout docs not working
N/A
N/A

Fix client side Dark Mode and layout docs

---

src/lib/components/codeBlock/QCodeBlock.svelte
src/lib/components/dialog/QDialog.svelte
src/lib/components/drawer/QDrawer.svelte
src/lib/components/footer/QFooter.svelte
src/lib/components/footer/props.ts
src/lib/components/header/QHeader.svelte
src/lib/components/icon/QIcon.svelte
src/lib/components/private/QDocsSection.svelte
src/routes/components/footer/+page.svelte
src/routes/components/icon/+page.svelte
src/routes/components/input/+page.svelte
src/routes/components/toolbar/+page.svelte

- Improve API and styles on some components
- Write docs for QFooter, QIcon and QInput
- Update props docs for QFooter
N/A
N/A

Docs refactor

---

src/lib/helpers/pageTitle.ts
src/routes/+layout.svelte
src/routes/privacy-policy/+page.svelte

- add privacy policy page (still needs to be linked)
N/A
N/A

feat: add privacy policy

---

eslint.config.js
src/lib/components/button/QBtn.scss
src/lib/components/button/QBtn.svelte
src/routes/+layout.svelte
src/routes/+page.svelte
src/routes/components/tabs/+page.svelte

- fix top margin - only for home page
- add a button to copy the npm create command to clipboard
- fix QBtn styles

Fixes optimizations

---

src/lib/components/drawer/QDrawer.svelte
src/lib/components/footer/QFooter.scss
src/lib/components/footer/QFooter.svelte
src/lib/components/header/QHeader.scss
src/lib/components/header/QHeader.svelte
src/lib/components/toolbar/QToolbar.scss
src/lib/components/toolbar/index.scss
src/lib/css/_components.scss
src/lib/css/mixins/_index.scss
src/lib/css/mixins/_toolbar.scss

- Remove toolbar inside QHeader and QFooter to avoid user styles problems
N/A
N/A

Toolbar fix

---

.github/workflows/npmpublish.yml

- upgrade publish ci script
N/A
N/A

ci: upgrade publish script

---

.github/workflows/pages.yml
svelte.config.js

- fix: remove "base" from docs build
N/A
N/A

fix: remove "base" from docs build

---

src/lib/classes/Quaff.svelte.ts
src/lib/components/drawer/QDrawer.scss
src/lib/components/drawer/QDrawer.svelte
src/lib/components/drawer/props.ts
src/lib/components/private/QApi.svelte
src/lib/components/private/QDocs.svelte
src/routes/+layout.svelte
src/routes/components/+page.svelte
src/routes/components/tooltip/+page.svelte
src/routes/utils/quaff/+page.svelte

- Add a breakpoint utility to the Quaff class
- Add QDrawer touch handler
- Make main layout more mobile-friendly (not perfect yet)
- Fix some styles
N/A
Closes #83

First step for mobile-friendly

---

src/lib/components/layout/QLayout.svelte
src/lib/components/private/QDocs.svelte
src/routes/+layout.svelte
src/routes/utils/+page.svelte

- Fix the issue where the page would be black on reload on mobile at `/components`
- Fill the landing page for `/utils`
- Prevent docs pages to expand beyond 1280px (`lg` breakpoint)
- Prevent the doc title/description card to have the title and description align inline on some screen widths
N/A
N/A

Layout fix

---

src/lib/components/private/QDocs.svelte
src/routes/+page.svelte
src/routes/components/+page.svelte
src/routes/components/avatar/+page.svelte
src/routes/components/button/+page.svelte
src/routes/components/chip/+page.svelte
src/routes/components/icon/+page.svelte
src/routes/components/list/+page.svelte

- remove `assets` in app paths
N/A
N/A

refactor: remove `assets` in app paths

---

README.md
src/routes/utils/+page.svelte

- Change readme early dev notice
- Fix wrong paths in `/utils`
N/A
N/A

fix: readme notice and utils paths

---

src/lib/css/index.scss

refactor: remove disabled css layer

---

src/lib/components/button/QBtn.svelte
src/lib/components/button/props.ts
src/lib/components/expansion-item/QExpansionItem.scss
src/lib/components/expansion-item/QExpansionItem.svelte
src/lib/components/expansion-item/docs.ts
src/lib/components/expansion-item/props.ts
src/lib/components/index.ts
src/lib/components/list/QItem.svelte
src/lib/css/_components.scss
src/routes/+layout.svelte
src/routes/components/+page.svelte
src/routes/components/expansion-item/+page.svelte

- Implement the API for the new QExpansionItem component
- Write docs for QExpansionItem
- Add `color` and `tag` props for QBtn
N/A
N/A

Add the expansion item component

---

src/lib/components/expansion-item/QExpansionItem.svelte

fix: prevent focus after click on disabled item and remove console.log

---

.github/workflows/pages.yml

fix: add plugin generation to be able to deploy to gh pages
